name: Build PR

on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Convert and publish AsciiDoctor
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Convert AsciiDoc
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "./.github/workflows/asciidoc.sh"
    - name: Save AsciiDoc
      uses: actions/upload-artifact@v1
      with:
        name: Docs
        path: ./output/
